//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDataEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMusicEntities : DbContext
    {
        public DBMusicEntities()
            : base("name=DBMusicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Albums> Albums { get; set; }
        public virtual DbSet<ArtistPlayer> ArtistPlayer { get; set; }
        public virtual DbSet<Artists> Artists { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Ganres> Ganres { get; set; }
        public virtual DbSet<MusicPlayers> MusicPlayers { get; set; }
        public virtual DbSet<SongGanre> SongGanre { get; set; }
        public virtual DbSet<Songs> Songs { get; set; }
    }
}
