//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistPlayer
    {
        public int AP_id { get; set; }
        public int AP_artId { get; set; }
        public int Ap_playerId { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual MusicPlayer MusicPlayer { get; set; }
    }
}
